### ISSUE TITLE
TypeError: iteration over a 0-d tensor

### ISSUE THREAD

**Issue by km1994** [vanzytay/pytorch_sentiment_rnn#8]
I'm run your code,but it did't work and had a error .What should i do?

Traceback (most recent call last):
  File "main_pf.py", line 196, in <module>
    train()
  File "main_pf.py", line 156, in train
    hidden = repackage_hidden(hidden)
  File "main_pf.py", line 126, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "main_pf.py", line 126, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "main_pf.py", line 126, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "main_pf.py", line 126, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "main_pf.py", line 126, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "main_pf.py", line 126, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "main_pf.py", line 126, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "main_pf.py", line 126, in <genexpr>
    return tuple(repackage_hidden(v) for v in h)
  File "main_pf.py", line 126, in repackage_hidden
    return tuple(repackage_hidden(v) for v in h)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 360, in __iter__
    raise TypeError('iteration over a 0-d tensor')
TypeError: iteration over a 0-d tensor

**Comment by BuaaAlban** [comment]
have you solved the problem?

**Comment by vanzytay** [comment]
@BuaaAlban No, this repository is not maintained anymore. I just made it for fun to try out pytorch when it came out.
